name: ci

on:
  push:
    branches:
    tags:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'dk.sh'
      - 'Makefile'
      - '.github/dependabot.yml'
      - '.github/FUNDING.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'dk.sh'
      - 'Makefile'
      - '.github/dependabot.yml'
      - '.github/FUNDING.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: app
            context: base.alpine
            dockerfile: base.alpine/Dockerfile
          - image: buildgo
            context: build.go
            dockerfile: build.go/Dockerfile
          - image: scratch
            context: base.scratch
            dockerfile: base.scratch/Dockerfile
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build ${{ matrix.image }} image
        run: docker build ${{ matrix.context }} -f ${{ matrix.dockerfile }}
